### ISSUE TITLE
Code does not compile?

### ISSUE THREAD

**Issue by jdwolin** [millerlp/Time_lapse_arducam#1]
Great looking script.  I built your board but the code does not seem to compile?  Any thoughts on why this is having problems?  Perhaps a library has been updated?

/Users/Jason Wolin/Dropbox/My Hobbies/Timelapse/Timelapse.ino: In function 'void setup()':
C:/Users/Jason Wolin/Dropbox/My Hobbies/Timelapse/Timelapse.ino:291:10: error: 'class DateTime' has no member named 'toString'
pinMode(SCL, INPUT);  // Disable I2C again
^
C:/Users/Jason Wolin/Dropbox/My Hobbies/Timelapse/Timelapse.ino:337:24: error: 'FIFO_PWRDN_MASK' was not declared in this scope
digitalWrite(REDLED, HIGH); // turn on error LED
^
C:/Users/Jason Wolin/Dropbox/My Hobbies/Timelapse/Timelapse.ino:339:24: error: 'LOW_POWER_MODE' was not declared in this scope
// Transfer data from ArduCam to the SD card
^
C:/Users/Jason Wolin/Dropbox/My Hobbies/Timelapse/Timelapse.ino: In function 'void loop()':
C:/Users/Jason Wolin/Dropbox/My Hobbies/Timelapse/Timelapse.ino:571:9: error: 'class DateTime' has no member named 'toString'
start_capture = 0;
^
C:\Users\Jason Wolin\.platformio\lib\RTClib\RTClib.cpp: In constructor 'DateTime::DateTime(uint32_t)':
C:\Users\Jason Wolin\.platformio\lib\RTClib\RTClib.cpp:86:18: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
if (days < 365 + leap)
^
C:/Users/Jason Wolin/Dropbox/My Hobbies/Timelapse/Timelapse.ino: In function 'void enableArduCam()':
C:/Users/Jason Wolin/Dropbox/My Hobbies/Timelapse/Timelapse.ino:1003:25: error: 'LOW_POWER_MODE' was not declared in this scope
C:/Users/Jason Wolin/Dropbox/My Hobbies/Timelapse/Timelapse.ino: In function 'DateTime startTIMER2(DateTime)':
C:/Users/Jason Wolin/Dropbox/My Hobbies/Timelapse/Timelapse.ino:1321:7: error: 'class RTC_DS3231' has no member named 'enable32kHz'
*** [.pioenvs\nanoatmega328\src\Timelapse.ino.cpp.o] Error 1
 [ERROR] Took 12.70 seconds

**Comment by millerlp** [comment]
Some of those errors look like the result of using the wrong RTClib library. Are you using the version from my repository: https://github.com/millerlp/RTClib ?

**Comment by jdwolin** [comment]
Yes, that was it!  Perfect.  Thank you for your help.
